//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

extension PostmonSwiftAPI {


open class DefaultAPI {
    /**
     Retorna os dados do endereço para o CEP passado
     
     - parameter cep: (path) Valor do CEP com apenas os 8 digitos. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCEPData(cep: String, completion: @escaping ((_ data: CEPResponse?,_ error: Error?) -> Void)) {
        getCEPDataWithRequestBuilder(cep: cep).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Retorna os dados do endereço para o CEP passado
     - GET /cep
     - Retorna os dados do endereço para o CEP passado. CEP deve ser enviado no formato de 8 dígitos.
     - parameter cep: (path) Valor do CEP com apenas os 8 digitos. 
     - returns: RequestBuilder<CEPResponse> 
     */
    open class func getCEPDataWithRequestBuilder(cep: String) -> RequestBuilder<CEPResponse> {
        var path = "/cep"
        let cepPreEscape = "\(APIHelper.mapValueToPathItem(cep))"
        let cepPostEscape = cepPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cep}", with: cepPostEscape, options: .literal, range: nil)
        let URLString = PostmonSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CEPResponse>.Type = PostmonSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
}
