//
// CEPResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CEPResponse: Codable {

    public var estado: String
    public var logradouro: String
    public var cidade: String?
    public var bairro: String?
    public var estadoInfo: EstadoInfo?
    public var cidadeInfo: CidadeInfo?

    public init(estado: String, logradouro: String, cidade: String?, bairro: String?, estadoInfo: EstadoInfo?, cidadeInfo: CidadeInfo?) {
        self.estado = estado
        self.logradouro = logradouro
        self.cidade = cidade
        self.bairro = bairro
        self.estadoInfo = estadoInfo
        self.cidadeInfo = cidadeInfo
    }


}

