//
// CidadeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CidadeInfo: Codable {

    public var areaKm2: String?
    public var codigoIbge: String?

    public init(areaKm2: String?, codigoIbge: String?) {
        self.areaKm2 = areaKm2
        self.codigoIbge = codigoIbge
    }

    public enum CodingKeys: String, CodingKey { 
        case areaKm2 = "area_km2"
        case codigoIbge = "codigo_ibge"
    }


}

