//
// EstadoInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EstadoInfo: Codable {

    public var areaKm2: String?
    public var codigoIbge: String?
    public var nome: String?

    public init(areaKm2: String?, codigoIbge: String?, nome: String?) {
        self.areaKm2 = areaKm2
        self.codigoIbge = codigoIbge
        self.nome = nome
    }

    public enum CodingKeys: String, CodingKey { 
        case areaKm2 = "area_km2"
        case codigoIbge = "codigo_ibge"
        case nome
    }


}

